In [1]:
import pandas as pd
import numpy as np
import pickle

In [7]:
def posterior_test(X, bin_ranges, bin_posteriors, ratio):
    num_bin = len(bin_ranges[0]) -1
    num_var = len(bin_ranges)
    posteriors = np.ones([len(X), num_var]) * ratio
    for i, bin_range in enumerate(bin_ranges):
        for j in range(num_bin):
            mask = (bin_range[j] <= X[:,i]) & (X[:,i] < bin_range[j+1])
            posteriors[:, i][mask] = bin_posteriors[i, j]
    return posteriors

In [3]:
with open('bin_posterior.pickle', 'rb') as f:
    bin_ranges = pickle.load(f)
    bin_posteriors = pickle.load(f)
    ratio_train = pickle.load(f)

In [4]:
df_test = pd.read_csv('test.csv')

In [5]:
X_test = df_test.drop(['ID_code'], axis=1).values

In [8]:
post_test =  posterior_test(X_test, bin_ranges, bin_posteriors, ratio_train)
print('done')

done

In [9]:
post_names = ['post_{}'.format(i) for i in range(200)]
df_post_test = pd.DataFrame(post_test, columns=post_names)
df_post_test = pd.concat([df_test['ID_code'], df_post_test], axis=1)
df_post_test.to_csv('test_posterior.csv', index=False)

In [10]:
df_post_test.head()

,ID_code,post_0,post_1,post_2,post_3,post_4,post_5,post_6,post_7,post_8,...,post_190,post_191,post_192,post_193,post_194,post_195,post_196,post_197,post_198,post_199
0,test_0,0.082522,0.215606,0.104028,0.111598,0.095737,0.088279,0.110281,0.105910,0.103234,...,0.085913,0.119865,0.121429,0.107656,0.111957,0.124498,0.102124,0.100592,0.102414,0.103460
1,test_1,0.089460,0.098220,0.089679,0.097995,0.098291,0.109465,0.098079,0.102533,0.097368,...,0.137255,0.106242,0.115204,0.090121,0.101858,0.095176,0.082106,0.086429,0.085247,0.092366
2,test_2,0.098492,0.085714,0.080065,0.111732,0.099546,0.133094,0.088366,0.093111,0.103086,...,0.088493,0.104115,0.094883,0.098575,0.098170,0.118173,0.092166,0.136578,0.092343,0.099542
3,test_3,0.089460,0.103409,0.104482,0.094520,0.095996,0.101332,0.088348,0.097356,0.096796,...,0.108805,0.106936,0.107254,0.097453,0.105788,0.149837,0.097087,0.089120,0.109551,0.100451
4,test_4,0.098023,0.093153,0.119444,0.099551,0.100120,0.095895,0.122488,0.104681,0.094038,...,0.104945,0.107371,0.105486,0.097954,0.099614,0.090956,0.081149,0.137841,0.108890,0.103460